import {Platform, StyleSheet, Text, View} from 'react-native';
import {
  widthPercentageToDP as wp,
  heightPercentageToDP as hp,
} from 'react-native-responsive-screen';
import {COLORS, SIZES} from '../../../util/Theme';

export const styles = StyleSheet.create({
  container: {flex: 1, backgroundColor: COLORS.white},
  profileIMG: {
    width: 40,
    height: 40,
    borderRadius: 100,
    borderColor: COLORS.gray,
    overflow: 'hidden',
    borderWidth: 0.8,
  },
  iconSearch: {position: 'absolute', right: 10, top: 8},
  nameContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.disabled,
    paddingVertical: 10,
    paddingHorizontal: 4,
  },
  flexCenter: {flex: 1, flexDirection: 'row', alignItems: 'center'},
  txtblack12: {
    fontSize: 12,
    color: COLORS.black,
    marginStart: 4,
    fontWeight: 'bold',
  },
  myProfile: {
    textAlign: 'center',
    fontSize: 18,
    color: COLORS.primary,
    fontWeight: 'bold',
    //marginTop: 10,
  },
  getingClg: {
    fontSize: 14,
    color: COLORS.black,
    fontWeight: 'bold',
    marginTop: 12,
    marginBottom: 5,
  },
  inputMSg: {
    borderColor: COLORS.gray,
    marginTop: 5,
    marginBottom: 12,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 15,
    color: COLORS.black,
    paddingVertical: Platform.OS == 'ios' && 12,
    // width: wp('92%'),
  },
  inputCollege: {
    borderColor: COLORS.gray,
    marginBottom: 12,
    borderWidth: 1,
    color: COLORS.black,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: Platform.OS == 'ios' && 12,
    //  width:wp('92%'),
  },
  inputCollegeArea: {
    borderColor: COLORS.gray,
    marginBottom: 12,
    borderWidth: 1,
    color: COLORS.black,
    borderRadius: 10,
    paddingHorizontal: 15,
    paddingVertical: Platform.OS == 'ios' && 12,
    minHeight: Platform.OS == 'ios' && 78,
    //  width:wp('92%'),
  },
  orDetilsTxt: {
    backgroundColor: COLORS.pink,
    paddingVertical: 10,
    textAlign: 'center',
    color: COLORS.white,
    fontWeight: 'bold',
    fontSize: 16,
    marginVertical: 10,
  },
  socialInput: {
    //height:48,
    borderColor: COLORS.gray,
    marginBottom: 12,
    borderWidth: 1,
    borderRadius: 10,
    paddingHorizontal: 5,
    paddingVertical: Platform.OS == 'ios' && 12,
  },
  circlelinkedin: {
    width: 30,
    height: 30,
    borderRadius: 16,
    backgroundColor: COLORS.primary,
    position: 'absolute',
    left: 10,
    top: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circlefb: {
    width: 30,
    height: 30,
    borderRadius: 16,
    backgroundColor: COLORS.blue,
    position: 'absolute',
    left: 10,
    top: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  circleInsta: {
    width: 30,
    height: 30,
    borderRadius: 16,
    position: 'absolute',
    left: 10,
    top: 12,
    backgroundColor: COLORS.pink,
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialInput1: {
    color: COLORS.black,
    color: COLORS.black,
    borderRadius: 10,
    paddingHorizontal: 34,
    // width: wp('92%'),
  },
  textContainer: {backgroundColor: COLORS.lightYellow},
  warryContainer: {
    width: SIZES.width * 0.9,
    alignSelf: 'center',
    paddingVertical: 10,
    flexDirection: 'row',
  },
  warningMsg: {
    marginHorizontal: 5,
    color: COLORS.black,
    textAlign: 'left',
    //width: SIZES.width * 0.8,
  },
  deleteDesc: {
    fontSize: 14,
    color: COLORS.black,
    marginTop: 5,
    marginBottom: 2,
    color: COLORS.darkRed,
  },

  phoneContainerStyle: {
    backgroundColor: COLORS.white,
    color: COLORS.black,
    borderRadius: 10,
    height: 52,
    borderColor: COLORS.gray,
    marginBottom: 5,
    borderWidth: 1,
    alignItems: 'center',
    // alignSelf: 'center',
    // width: wp('92%'),
    width: 'auto',
  },
  phoneTextContainerStyle: {
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    height: 46,
    padding: 0,
    backgroundColor: COLORS.white,
  },
  phoneFlugBtnStyle: {
    backgroundColor: COLORS.white,
    width: 62,
    height: 46,
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    overflow: 'hidden',
    alignSelf: 'center',
  },
  phoneTextInputStyle: {
    backgroundColor: COLORS.white,
    marginStart: -5,
    height: 45,
    fontSize: 14,
    padding: 0,
    color: COLORS.black,
  },
  countrycodeStyle: {
    height: 28,
    paddingVertical: 5,
    marginStart: -5,
    backgroundColor: COLORS.white,
    color: COLORS.black,
    fontSize: 14,
    fontWeight: 'normal',
    textAlign: 'center',
  },
  //drop down
  dropdownTitle: {color: COLORS.black, fontSize: 14},
  dropdownLabel: {color: COLORS.black, fontSize: 15, paddingStart: 10},
  dropdownicon: {tintColor: COLORS.black, height: 18, width: 18, marginEnd: 10},
  dropdoenContainer: {
    backgroundColor: COLORS.white,
    borderWidth: 1,
    borderColor: COLORS.gray,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'ios' ? 12 : 6,
    //width: wp('92%')
    height: 52,
    alignSelf: 'center',
    fontSize: 14,
    marginTop: 5,
    marginBottom: 15,
  },
  dropdownPlaceholder: {color: COLORS.black, fontSize: 14, fontWeight: 'bold'},
  removeBtn: {
    justifyContent: 'center', // Vertically center content
    alignItems: 'center', // Horizontally center content
    paddingHorizontal: 10,
    marginBottom: 12,
    paddingBottom: 10,
  },
});
